name: TrollBossPE
main: xXSirGamesXx\TrollBoss\TrollBoss
api: 3.0.0-ALPHA6
version: 1.0.0
description: "Plugin skeleton"

commands:
  trollboss:
    description: "example command description"
    permission: troll.cmd
    aliases: ["tb"]

permissions:
  troll.cmd:
    default: op # true = anyone can use the command, false = no one can use the command and op = only opped players can use the command
    description: "All troll commands"
  troll.cmd.help:
    default: op
    description: "TrollBoss command help"
